# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from ..import fields as custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', custom_fields.ArticleField(max_length=50, verbose_name='Article')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('cost', custom_fields.PositiveDecimalField(decimal_places=2, max_digits=10, verbose_name='Cost')),
                ('price', custom_fields.PositiveDecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('count', custom_fields.PositiveDecimalField(decimal_places=2, max_digits=10, verbose_name='Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='webstore.ProductCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'ProductCategories',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='StoreAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=100, verbose_name='Line1')),
                ('line2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line2')),
                ('street', models.CharField(max_length=40, verbose_name='Street')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=40, null=True, verbose_name='State')),
                ('zip', models.CharField(max_length=20, verbose_name='ZIP')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.StoreAddress',
                                    verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.ProductCategory',
                                    verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.Store',
                                    verbose_name='Store'),
        ),
    ]
